# Generated by Django 3.2.25 on 2024-06-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Flash_coin',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='collection',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
