# Generated by Django 3.2.25 on 2024-06-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20240603_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bought_QN',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='filled_QN',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
