# Generated by Django 3.2.25 on 2024-05-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QN', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='is_released',
            field=models.BooleanField(default=True, verbose_name='是否已发行'),
        ),
    ]
