# Generated by Django 3.2.25 on 2024-05-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QN', '0002_alter_survey_is_released'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='is_released',
            field=models.BooleanField(default=False, verbose_name='是否已发行'),
        ),
    ]
