# Generated by Django 3.2.25 on 2024-05-31 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QN', '0003_alter_survey_is_released'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='arg3',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='第三选项'),
        ),
    ]
