# Generated by Django 3.2.25 on 2024-05-31 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QN', '0004_question_arg3'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='do_time',
            field=models.DateTimeField(null=True, verbose_name='填写时间'),
        ),
    ]
