# Generated by Django 3.2.25 on 2024-06-02 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QN', '0005_survey_do_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='left_num',
            field=models.IntegerField(default=0, verbose_name='剩余填写数量'),
        ),
        migrations.AddField(
            model_name='option',
            name='max_num',
            field=models.IntegerField(default=0, verbose_name='最大填写数量'),
        ),
    ]
