# Generated by Django 3.2.25 on 2024-06-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QN', '0006_auto_20240602_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='is_square',
            field=models.BooleanField(default=False, verbose_name='是否已发布到广场'),
        ),
    ]
