name: 'Deployment To Cloud'

on:
  workflow_dispatch:
  push:
    branches: [main]
  
jobs:
  build-docker-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    
    - name: Generate timestamp
      id: timestamp
      run: echo "::set-output name=timestamp::$(date +%s)"

    - name: Build the Docker image
      working-directory: ./flash-cradle/
      run: docker build . --tag ${{ secrets.DOCKER_USERNAME }}/flashq-frontend:${{ steps.timestamp.outputs.timestamp }}

    - name: Push the Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/flashq-frontend:${{ steps.timestamp.outputs.timestamp }}
    
    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: SSH to Remote Server and Deploy
      run: |
        sshpass -p "${{ secrets.PASSWORD }}" ssh -o StrictHostKeyChecking=no "${{ secrets.USERNAME }}"@"${{ secrets.TARGET }}" << 'EOF'
          sh /root/k8stest/update.sh ${{ steps.timestamp.outputs.timestamp }}
        EOF
    


  
